# Generated by Django 2.2.5 on 2019-11-07 18:48

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block',
            field=models.BooleanField(default=False, verbose_name='Bloquear usuario'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile/perfil_img.jpg', null=True, upload_to=register.models.custom_upload),
        ),
    ]
